name: React App Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: install java
      uses: actions/setup-java@v3
      with: 
        java-version: 11
        distribution: adopt
        cache: gradle

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Fastlane
      run: |
        sudo chown -R $USER /var/lib/gems/3.0.0
        sudo gem cleanup 
        gem update bundler
        sudo gem install bundler
        sudo gem install fastlane -NV
        bundle install

    - name: Execute Fastlane
      run: |
        bundle exec fastlane ticket

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-platform: 'platforms;android-29'

    - name: Create local.properties file
      run: echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties  

    - name: Build Android app
      run: |
           npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
           cd android && chmod +x gradlew
           ./gradlew assembleDebug --warning-mode all
    - name: Upload application
      uses: actions/upload-artifact@v2
      with:
         name: app
         path: android/app/build/outputs/**/*.apk
         retention-days: 3   


    - name: Sign AAB
      id: sign
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/ .apk
        signingKeyBase64: ${{ secrets.COFFEE_APP }}
        alias: COFFEE_APP
        keyStorePassword: codemagic 
        keyPassword: codemagic            

    - name: Deploy to Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: codemagic.json
        packageName: Coffee-Shop-App
        releaseFile: android/app/build/outputs/**/*.apk
        track: beta               
         
